source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'STMReactiveViewController', :exclusive => true do
  pod "STMReactiveViewController", :path => "../"
  pod 'LoremIpsum'
end

target 'Tests', :exclusive => true do
  pod "STMReactiveViewController", :path => "../"

  
end
